/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nt_1;

import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Alumno
 */
public class CConsulta extends javax.swing.JFrame {
public boolean empty = true;
public Connection coneccion;
public Statement sentencia;
public String bd="pais";
public String usuario="root";
public String contraseña="123456";
public String url="jdbc:mysql://localhost/"+bd;
public static ResultSet rs1;
public String estado;
public TableRowSorter trs;
    /**
     * Creates new form CConsulta
     */
    public CConsulta() {
        initComponents();
        PrepararBaseDeDatos();
        CargarDatos();
        
    }
        public void PrepararBaseDeDatos(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            coneccion = DriverManager.getConnection(url, usuario, contraseña);
            if (coneccion != null){
                System.out.println("Conexion a base de datos ... OK");
            }
        } catch (Exception e){
            System.out.println("No se puedo conectar con la base de datos");
        }
        try{
            sentencia = coneccion.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        }catch(Exception e){
            System.out.println("Error al crear objeto consulta");
        }
    }
        
    public void CargarDatos(){
        DefaultTableModel tabla = (DefaultTableModel) tblProvincia.getModel();
        try{
            rs1 = sentencia.executeQuery("SELECT * FROM pais.provincia ORDER BY id_provincia");
            int f=0;
            while(rs1.next()){
                tabla.addRow(new Object[]{"",""});
                tblProvincia.setValueAt(rs1.getString("id_provincia"), f, 0);
                tblProvincia.setValueAt(rs1.getString("nombre"), f, 1);
                f++;
            }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpScroll = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProvincia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSeleccion = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        txtSelector = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProvincia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProvincia.setFillsViewportHeight(true);
        tblProvincia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblProvincia);

        scpScroll.setViewportView(jScrollPane1);

        jLabel1.setText("Buscar");

        btnSeleccion.setText("Seleccionar");
        btnSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imrpimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        txtSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        txtSelector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSelectorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImprimir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSeleccion)
                    .addComponent(txtSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(scpScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
String id=(String)tblProvincia.getValueAt(tblProvincia.getSelectedRow(), 0);
String nom=(String)tblProvincia.getValueAt(tblProvincia.getSelectedRow(),1);
Provincia1.txtId.setText(id);
Provincia1.txtNombre.setText(nom);
try{
    rs1.absolute(tblProvincia.getSelectedRow());
    Provincia1.rs.absolute(rs1.getRow()+1);
    System.out.println(rs1.getRow()+1);
//    while (rs1.next()){
//        if(rs1.getString("nombre").equals(nom)){
//            System.out.println(rs1.getRow());
//            break;
//        }
//        System.out.println(rs1.getRow());
//    }
//Provincia1.rs.absolute(rs1.getRow());
}catch(Exception e){
    
}
this.setVisible(false);
    }//GEN-LAST:event_btnSeleccionActionPerformed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void txtSelectorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSelectorKeyTyped
        txtSelector.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent Ke){
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtSelector.getText(), 1));
            }
        }); 
        trs = new TableRowSorter(tblProvincia.getModel());
        tblProvincia.setRowSorter(trs);
    }//GEN-LAST:event_txtSelectorKeyTyped

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        String dir_current = System.getProperty("user.dir") ;
        String repo = dir_current+"/src/nt_1/report1.jrxml";
        System.out.println(repo);
        try {
            JasperReport reporte = JasperCompileManager.compileReport(repo);
            JasperPrint print = JasperFillManager.fillReport(reporte, null, this.coneccion);
            JasperViewer view = new JasperViewer(print, false);
            view.setVisible(true);
        }catch(JRException e){
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scpScroll;
    private javax.swing.JTable tblProvincia;
    private javax.swing.JTextField txtSelector;
    // End of variables declaration//GEN-END:variables
}
