/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nt_1;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class Provincia1 extends javax.swing.JFrame {
public boolean empty = true;
public Connection coneccion;
public Statement sentencia;
public String bd="pais";
public String usuario="root";
public String contraseña="123456";
public String url="jdbc:mysql://localhost/"+bd;
public static ResultSet rs;
public String estado;
    public Provincia1() {
        initComponents();
        PrepararBaseDeDatos();
        CargarConsulta();
        CargarDatos();
        if(empty){
            txtNombre.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnAceptar.setEnabled(false);
            btnBaja.setEnabled(false);
            btnModificar.setEnabled(false);
            btnConsulta.setEnabled(false);
            btnSiguiente.setEnabled(false);
            btnUltimo.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnPrimero.setEnabled(false);
        }else{
            txtNombre.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnAceptar.setEnabled(false);
        }
    }
    public void PrepararBaseDeDatos(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            coneccion = DriverManager.getConnection(url, usuario, contraseña);
            if (coneccion != null){
                System.out.println("Conexion a base de datos ... OK");
            }
        } catch (Exception e){
            System.out.println("No se puedo conectar con la base de datos");
        }
        try{
            sentencia = coneccion.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        }catch(Exception e){
            System.out.println("Error al crear objeto consulta");
        }
    }
    void CargarConsulta(){
        try{
            rs = sentencia.executeQuery("SELECT * FROM pais.provincia ORDER BY id_provincia");
            rs.next();
          if(rs.isFirst()){
            txtId.setText(rs.getString("id_provincia"));
            txtNombre.setText(rs.getString("nombre"));
            System.out.println("No Vacio");
            empty = false;
        }else{
            System.out.println("Vacio");
        }   
        }catch (Exception e){
            
        }
    }
        void CargarConsultaMod(){
        try{
            rs = sentencia.executeQuery("SELECT * FROM pais.provincia WHERE (`id_provincia` = '"+Integer.parseInt(txtId.getText())+"');");
            rs.next();
          if(rs.isFirst()){
            txtId.setText(rs.getString("id_provincia"));
            txtNombre.setText(rs.getString("nombre"));
            System.out.println("No Vacio");
            empty = false;
        }else{
            System.out.println("Vacio");
        }   
        }catch (Exception e){
            
        }
    }
    void CargarDatos(){
        try{
            txtId.setText(rs.getString("id_provincia"));
            txtNombre.setText(rs.getString("nombre"));
        }catch(Exception e){
            btnBaja.setEnabled(false);
            btnModificar.setEnabled(false);
            btnSiguiente.setEnabled(false);
            btnUltimo.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnPrimero.setEnabled(false);
        }
    }
    void Activar(){
        txtNombre.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAceptar.setEnabled(false);
        btnBaja.setEnabled(true);
        btnModificar.setEnabled(true);
        btnConsulta.setEnabled(true);
        btnSiguiente.setEnabled(true);
        btnUltimo.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnPrimero.setEnabled(true);
    }
    void Desactivar(){
        txtNombre.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAceptar.setEnabled(true);
        btnBaja.setEnabled(false);
        btnModificar.setEnabled(false);
        btnConsulta.setEnabled(false);
        btnSiguiente.setEnabled(false);
        btnUltimo.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnPrimero.setEnabled(false);
    }
//    public void IsEmpty(){
//        try{
//        rs = ConectarDatos("SELECT * FROM provincia");
//        rs.next();
//        if(rs.isFirst()){
//            txtId.setText(rs.getString("id_provincia"));
//            txtNombre.setText(rs.getString("nombre"));
//            System.out.println("No Vacio");
//            empty = false;
//        }else{
//            System.out.println("Vacio");
//
//        }    
//        }catch(Exception e){
//
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Deny.png"))); // NOI18N
        btnCancelar.setActionCommand("X");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnUltimo.setText(">>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnAnterior.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnPrimero.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnPrimero.setText("<<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("Codigo");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        txtId.setEnabled(false);

        btnAlta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAlta.setText("ALTA");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnBaja.setText("BAJA");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnModificar.setText("MOD");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnConsulta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnConsulta.setText("CONSULTA");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Check2.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrimero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUltimo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsulta))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaja)
                    .addComponent(btnModificar)
                    .addComponent(btnConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Activar();
        try{
            CargarDatos();
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        Desactivar();
        txtNombre.setText("");
        boolean b = false;
        try{
            estado = "Alta";
            try{
                int row;
                int txt;
                rs.first(); 
                row = rs.getRow();
                txt = (rs.getInt("id_provincia"));
                System.out.println(row);
                System.out.println(rs.getString("nombre"));
                System.out.println(txt);
//                sentencia.execute("UPDATE `pais`.`provincia` SET `id_provincia` = '"+row+"' WHERE (`id_provincia` = '"+txt+"');");
//                rs = sentencia.executeQuery("SELECT * FROM pais.provincia");
//                rs.absolute(row);
                while (rs.next()){
                    if(row != txt){
                        System.out.println("Hay un lugar");
                        txtId.setText(Integer.toString(row));
                        b = true;
                        break;
                    }else{
                        row = rs.getRow();
                        txt = (rs.getInt("id_provincia"));
                        System.out.println(row);
                        System.out.println(rs.getString("nombre"));
                        System.out.println(txt);
                    }
//                    row = rs.getRow();
//                    txt = (rs.getInt("id_provincia"));
//                    System.out.println(row);
//                    System.out.println(rs.getString("nombre"));
//                    System.out.println(txt);
//                    sentencia.execute("UPDATE `pais`.`provincia` SET `id_provincia` = '"+row+"' WHERE (`id_provincia` = '"+txt+"');");
//                    rs = sentencia.executeQuery("SELECT * FROM pais.provincia");
//                    rs.absolute(row);
                }
            }catch(Exception e){
                e.printStackTrace();
            }
            if (b == false){
                rs.last();
                int a = rs.getInt("id_provincia")+1;
                txtId.setText(Integer.toString(a));      
            }
        }catch(Exception e){
            txtId.setText("1");
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Desactivar();
        try{
            estado = "Modificar";
            int a = rs.getInt("id_provincia");
            txtId.setText(Integer.toString(a));
        }catch(Exception e){
            txtId.setText("1");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try{
            if(rs.isLast()){
                
            }else{
                rs.next();
                txtId.setText(rs.getString("id_provincia"));
                txtNombre.setText(rs.getString("nombre"));
            }
        }
        catch(Exception e){
            System.out.println(e);
        }


//        BasedeDatos bd=new BasedeDatos();
//        try{
//            rs.first();
//            txtId.setText(rs.getString("id_provincia"));
//            txtNombre.setText(rs.getString("nombre"));
////        rs = bd.ConectarDatos("SELECT * FROM provincia WHERE id_provincia = 2");
////        System.out.println(select);
////        System.out.println(cant);
////            IsEmpty();
////            txtId.setText(rs.getString("id_provincia"));
////            txtNombre.setText(rs.getString("nombre"));
//        
//        }catch(Exception e){
//            
//        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try{
            if(rs.isFirst()){
                
            }else{
                rs.previous();
                txtId.setText(rs.getString("id_provincia"));
                txtNombre.setText(rs.getString("nombre"));
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
//        ResultSet rs=null;
//        BasedeDatos bd=new BasedeDatos();
//        try{
//        rs = bd.ConectarDatos("SELECT * FROM provincia WHERE id_provincia = 2");
//        System.out.println(select);
//        System.out.println(cant);
//        select --;
//        if (select <= 0){
//            select += 1;
//        }
//            IsEmpty();
////            txtId.setText(rs.getString("id_provincia"));
////            txtNombre.setText(rs.getString("nombre"));
//        }catch(Exception e){
//            
//        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        try{
            rs.first();
            txtId.setText(rs.getString("id_provincia"));
            txtNombre.setText(rs.getString("nombre"));
        }catch(Exception e){
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        try{
            rs.last();
            txtId.setText(rs.getString("id_provincia"));
            txtNombre.setText(rs.getString("nombre"));
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(estado == "Alta"){
            try{
                if (!txtNombre.getText().isEmpty()){
                    //                sentencia = coneccion.createStatement();
                    sentencia.execute("INSERT INTO `pais`.`provincia` (`id_provincia`, `nombre`) VALUES ('"+Integer.parseInt(txtId.getText())+"', '"+txtNombre.getText()+"');");
                    CargarConsulta();
                    rs.last();
                    CargarDatos();
                }else{
                    JOptionPane.showMessageDialog(null, "Debe escribir una provincia");
                    txtNombre.requestFocus();
                }
//                sentencia = coneccion.createStatement();
//                sentencia.execute("INSERT INTO `pais`.`provincia` (`id_provincia`, `nombre`) VALUES ('"+Integer.parseInt(txtId.getText())+"', '"+txtNombre.getText()+"');");
//                CargarConsulta();
//                rs.last();
//                CargarDatos();
            } catch (SQLException e){
                e.printStackTrace();
                System.out.println("No funca el Alta");
            }
            
        }else{
            try{
//                sentencia = coneccion.createStatement();
//                int i = Integer.parseInt(txtId.getText());
                String t = txtNombre.getText();
                sentencia.execute("UPDATE `pais`.`provincia` SET `nombre` = '"+txtNombre.getText()+"' WHERE (`id_provincia` = '"+Integer.parseInt(txtId.getText())+"');");
                CargarConsulta();
                while (rs.next()){
                    if(rs.getString("nombre").equals(t)){
                        break;
                    }
                }
//                rs.absolute(i);
                CargarDatos();
            } catch (SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al modificar registro, confirme que no este asociado a otra tabla");
            }
        }
        Activar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        int a;
        a = JOptionPane.showConfirmDialog(null, "Esta seguro que desea borrar el registro", "Atención", 0);
        if(a == 0){
            try{
//                sentencia = coneccion.createStatement();
                sentencia.execute("DELETE FROM `pais`.`provincia` WHERE (`id_provincia` = '"+Integer.parseInt(txtId.getText())+"');");
                CargarConsulta();
                rs.last();
                CargarDatos();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Error al borrar registro, confirme que no este asociado a otra tabla");
                e.printStackTrace();
            }
//            try{
//                int row;
//                int txt;
//                rs.first(); 
//                row = rs.getRow();
//                txt = (rs.getInt("id_provincia"));
//                System.out.println(row);
//                System.out.println(rs.getString("nombre"));
//                System.out.println(txt);
//                sentencia.execute("UPDATE `pais`.`provincia` SET `id_provincia` = '"+row+"' WHERE (`id_provincia` = '"+txt+"');");
//                rs = sentencia.executeQuery("SELECT * FROM pais.provincia");
//                rs.absolute(row);
//                while (rs.next()){
//                    row = rs.getRow();
//                    txt = (rs.getInt("id_provincia"));
//                    System.out.println(row);
//                    System.out.println(rs.getString("nombre"));
//                    System.out.println(txt);
//                    sentencia.execute("UPDATE `pais`.`provincia` SET `id_provincia` = '"+row+"' WHERE (`id_provincia` = '"+txt+"');");
//                    rs = sentencia.executeQuery("SELECT * FROM pais.provincia");
//                    rs.absolute(row);
//                }
//            }catch(Exception e){
//                e.printStackTrace();
//            }
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        CConsulta bp=new CConsulta();
        bp.setVisible(true);
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Localidad localidad=new Localidad();
        localidad.Alta();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provincia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provincia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provincia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provincia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provincia1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
